### ISSUE TITLE
To-Do List: Система автоматизации интеграций

### ISSUE THREAD

**Issue by lennoximus** [lennoximus/DSR-Practice-Project#1]
Разработать систему автоматизации интеграций. Само приложение - консольное.
- [ ] Реализовать поддержку следующих баз данных:
- MongoDB;
- PostgreSQL;
- MySQL
- [x] Настройка системы через xls-файл.
- [ ] Функция составления отчёта, содержащего:
- количество успешно смигрированных записей по каждой таблице/коллекции,
-  список записей, которые не удалось смигрировать с указанием причины (например, не удалось преобразовать значение в число)
